### ISSUE TITLE
What happens if you want to start a new community?

### ISSUE THREAD

**Issue by deavmi** [freifunk/meshkit#17]
What happens if you want to start a new community? And obviously it is not on the list.

![](http://i.imgur.com/Qw2DE1d.png?1)
![](http://i.imgur.com/eJphT0q.png?1)

I just went with the first one, even though I live not in germany but in South Africa.

**Comment by mmunz** [comment]
Hi,
adding new communities is documented here: http://doc.meshkit.freifunk.net/daily/html/communities/index.html (german only). If you need more help: you'll find me in #freifunk on ircnet and hackint (soma).

**Comment by deavmi** [comment]
@mmunz Okay. Thank you. :smile:
