### ISSUE TITLE
Remove Heppenheim and Bensheim from Meshkit

### ISSUE THREAD

**Issue by nazco** [freifunk/meshkit#20]
Hey, we've noticed that the meshkit builder under http://meshkit.freifunk.net/ contains configs for Bensheim and Heppenheim. This communities where dead and dissolved into Freifunk Rhein Neckar which is using the gluon firmware. So we think it would be better to remove this cities to prevent confusions.

**Comment by mmunz** [comment]
deleted in the luci repo, see https://github.com/openwrt/luci/commit/1d562672cdcfb84222b9e01ac07775d74e53c7cf
