### ISSUE TITLE
TP-Link WR841N Ver10

### ISSUE THREAD

**Issue by tillhanke** [freifunk/meshkit#21]
The Firmware for the TP-Link WR841N Ver10 is not generated by the Meshkit.

OpenWRT firmware is here:
https://forum.openwrt.org/viewtopic.php?id=59577

**Comment by FreifunkUFO** [comment]
Dein Problem liegt nicht an Meshkit, sondern dass du Meshkit mit einem veralteten Openwrt (oder LEDE) verwendest!
Bitte mache ein Update von deinem Openwrt/Lede (via Imagebuilder)..
